# Generated by Django 4.2.3 on 2023-08-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variation',
            new_name='Discount',
        ),
    ]
