# Generated by Django 4.2.3 on 2023-08-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_rename_variation_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categories'},
        ),
    ]
