# Generated by Django 4.2.6 on 2023-10-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highlighted_features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
