# Generated by Django 4.2.3 on 2023-09-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_delete_orderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
