# Generated by Django 4.2.3 on 2023-10-11 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_cart_active_order_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
