# Generated by Django 4.2.3 on 2023-10-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_rename_product_cart_products_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
